services:
  asset-maintenance:
    build:
      dockerfile: Dockerfile.asset_maintenance
    command: python -u AIOps_Asset_Maintenance.py
    environment:
      - DATASET_DIR=${DATASET_DIR}
    image: ${FINAL_IMAGE_NAME}:asset-maintenance-ubuntu-20.04
    privileged: true
    volumes: 
      - ${DATASET_DIR}:/dataset
      - $PWD:/workspace
    working_dir: /workspace/AIOps
